version: '3'

services:
        dns:
                build: ../dns
                container_name: bind
                ports:
                        - "51.77.141.246:53:53/tcp"
                        - "51.77.141.246:53:53/udp"
                volumes:
                        - ../dns/etc:/etc/bind
